// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// StateMachineAliasSpec defines the desired state of StateMachineAlias.
type StateMachineAliasSpec struct {

	// A description for the state machine alias.
	Description *string `json:"description,omitempty"`
	// The name of the state machine alias.
	//
	// To avoid conflict with version ARNs, don't use an integer in the name of
	// the alias.
	//
	// Regex Pattern: `^(?=.*[a-zA-Z_\-\.])[a-zA-Z0-9_\-\.]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The routing configuration of a state machine alias. The routing configuration
	// shifts execution traffic between two state machine versions. routingConfiguration
	// contains an array of RoutingConfig objects that specify up to two state machine
	// versions. Step Functions then randomly choses which version to run an execution
	// with based on the weight assigned to each RoutingConfig.
	// +kubebuilder:validation:Required
	RoutingConfiguration []*RoutingConfigurationListItem `json:"routingConfiguration"`
}

// StateMachineAliasStatus defines the observed state of StateMachineAlias
type StateMachineAliasStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date the state machine alias was created.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// The date the state machine alias was last updated.
	// +kubebuilder:validation:Optional
	UpdateDate *metav1.Time `json:"updateDate,omitempty"`
}

// StateMachineAlias is the Schema for the StateMachineAliases API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type StateMachineAlias struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              StateMachineAliasSpec   `json:"spec,omitempty"`
	Status            StateMachineAliasStatus `json:"status,omitempty"`
}

// StateMachineAliasList contains a list of StateMachineAlias
// +kubebuilder:object:root=true
type StateMachineAliasList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StateMachineAlias `json:"items"`
}

func init() {
	SchemeBuilder.Register(&StateMachineAlias{}, &StateMachineAliasList{})
}
